server {
    listen 80;
    root /usr/share/nginx/html;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location = / {
        try_files /index.html =404;
    }

    location = /analytics {
        try_files /analytics.html =404;
    }

    location /api/shorten {
        set $shortener_upstream http://shortener-service:3001;
        proxy_pass $shortener_upstream;
    }

    location /api/analytics/ {
        set $analytics_upstream http://analytics-service:3002;
        proxy_pass $analytics_upstream;
    }

    location / {
        set $redirect_upstream http://redirect-service:3000;
        proxy_pass $redirect_upstream;
    }
}
